### ISSUE TITLE
possibly use GeneratedFile interface

### ISSUE THREAD

**Issue by lun-4** [kivikakk/htmlentities.zig#10]
at the moment the build step that precomputes the entities will add `src/entities.zig` to the project that uses the package, rather than the htmlentities package itself, as the cwd doesn't change on the step

```zig
    var out_file = try std.fs.cwd().createFile("src/entities.zig", .{});
    const formatted = try zig_tree.render(allocator);
    try out_file.writer().writeAll(formatted);
    out_file.close();
```

I am not sure if the GeneratedFile interface of zig build would work for this, would need to explore that myself. for now, package users would need to add `src/entities.zig` to their gitignore which is a bit hacky

another approach would be having a dedicated `zig build entities.zig` step that is only used for development of htmlentities which would generate the file, keeping it vendored for distribution (which is what already happens)

**Comment by kivikakk** [comment]
Hah, whoops. The dedicated build step seems like a pretty easy OK choice; I might do that this evening to at least get it building more cleanly immediately.

**Comment by kivikakk** [comment]
Trying [this approach](https://ziglang.org/learn/build-system/#generating-zig-source-code) now!
